local color = require("kanagawa-paper.lib.color")

local M = {}

---@param opts KanagawaConfig
---@param palette PaletteColors
---@return ThemeColors
M.get = function(opts, palette)
	---@type ThemeColors
	return {
		modes = {
			normal = palette.dragonYellow,
			insert = palette.dragonRed,
			visual = palette.springViolet1,
			replace = palette.dragonRed,
			command = palette.dragonYellow,
		},
		ui = {
			fg = palette.dragonWhite,
			fg_dim = palette.katanaGray,
			fg_dimmer = palette.dragonBlack5,
			fg_dark = palette.dragonBlack3,
			fg_reverse = palette.dragonBlack2,
			bg_m4 = palette.dragonBlack1,
			bg_m3 = palette.dragonBlack0,
			bg_m2 = palette.dragonBlack1,
			bg_m1 = palette.dragonBlack2,
			bg_dim = palette.dragonBlack1,
			bg = palette.dragonBlack3,
			bg_p1 = palette.dragonBlack4,
			bg_p2 = palette.dragonBlack5,
			bg_gutter = opts.gutter and palette.dragonBlack4 or "none",
			bg_cursorline = palette.dragonBlack4,
			bg_cursorline_alt = palette.dragonBlack5,
			bg_search = palette.springViolet1,
			bg_visual = palette.dragonBlack5,
			bg_statusline = palette.dragonBlack4,
			border = palette.dragonBlack6,
			header1 = palette.dragonViolet,
			header2 = palette.dragonOrange,
			special = palette.dragonAqua,
			nontext = palette.dragonBlack6,
			whitespace = palette.dragonBlack6,
			win_separator = palette.katanaGray,
			indent = palette.dragonBlack5,
			indent_scope = palette.dragonViolet,
			picker = palette.dragonRed,
			yank = palette.dragonBlack6,
			mark = palette.waveAqua2,
			scrollbar = palette.dragonBlack5,
			tabline = {
				bg = palette.dragonBlack0,
				fg_selected = palette.dragonWhite,
				bg_selected = palette.dragonBlack3,
				fg_inactive = palette.dragonBlack5,
				bg_inactive = palette.dragonBlack0,
				fg_alternate = palette.dragonPink,
				bg_alternate = palette.dragonBlack0,
				indicator = palette.dragonBlue,
			},
			pmenu = {
				fg = palette.dragonWhite,
				fg_sel = "none", -- This is important to make highlights pass-through
				fg_border = palette.dragonBlack5,
				bg_border = palette.dragonBlack4,
				bg = palette.dragonBlack4,
				bg_sel = palette.dragonBlack5,
				bg_sbar = palette.dragonBlack4,
				bg_thumb = palette.dragonBlack6,
			},
			float = {
				fg = palette.dragonWhite,
				bg = palette.dragonBlack3,
				fg_border = palette.katanaGray,
				bg_border = palette.dragonBlack3,
			},
		},
		accent = {
			accent1 = palette.dragonBlue,
			accent2 = palette.dragonOrange,
			accent3 = palette.waveAqua1,
			accent4 = palette.dragonGray3,
			accent5 = palette.dragonRed,
			invert = palette.dragonBlack4,
		},
		rainbow = {
			rainbow1 = palette.dragonRed,
			rainbow2 = palette.dragonPink,
			rainbow3 = palette.dragonBlue,
			rainbow4 = palette.dragonOrange2,
			rainbow5 = palette.dragonGreen,
			rainbow6 = palette.dragonAsh,
			rainbow7 = palette.dragonTeal,
		},
		syn = {
			attribute = palette.fujiWhite,
			comment = palette.katanaGray,
			docstring = palette.fujiWhite,
			constant = palette.dragonOrange,
			deprecated = palette.katanaGray,
			fun = palette.dragonYellow,
			identifier = palette.dragonWhite,
			keyword = palette.dragonWhite,
			member = palette.dragonWhite,
			number = palette.dragonOrange,
			operator = palette.dragonWhite,
			parameter = palette.dragonWhite,
			preproc = palette.dragonWhite,
			punct = palette.dragonAsh,
			regex = palette.dragonGreen2,
			statement = palette.dragonWhite,
			string = palette.dragonGreen2,
			symbol = palette.dragonWhite,
			type = palette.dragonBlue2,
			variable = palette.dragonWhite,
			-- special1 = "none",
			-- special2 = "none",
			-- special3 = "none",
			special1 = palette.dragonYellow,
			special2 = palette.dragonRed,
			special3 = palette.springViolet1,
			property = palette.dragonWhite,
		},
		vcs = {
			added = palette.dragonGreen,
			added_light = color(palette.dragonGreen):blend(palette.dragonBlack3, 0.9):to_hex(),
			removed = palette.dragonRed,
			removed_light = color(palette.dragonRed):blend(palette.dragonBlack3, 0.9):to_hex(),
			changed = palette.dragonYellow,
			changed_light = color(palette.dragonYellow):blend(palette.dragonBlack3, 0.9):to_hex(),
		},
		diff = {
			add = palette.dragonGreen,
			add_light = color(palette.dragonGreen):blend(palette.dragonBlack3, 0.9):to_hex(),
			delete = palette.dragonRed,
			delete_light = color(palette.dragonRed):blend(palette.dragonBlack3, 0.9):to_hex(),
			change = palette.dragonYellow,
			change_light = color(palette.dragonYellow):blend(palette.dragonBlack3, 0.9):to_hex(),
			text = palette.dragonBlue,
			text_light = color(palette.dragonBlue):blend(palette.dragonBlack3, 0.9):to_hex(),
			conflict_ours = palette.dragonGreen3,
			conflict_theirs = palette.dragonBlue5,
			conflict_ancestor = palette.dragonOrange2,
		},
		diag = {
			ok = palette.dragonGreen,
			ok_light = color(palette.dragonGreen):blend(palette.dragonBlack3, 0.92):to_hex(),
			error = palette.dragonRed,
			error_light = color(palette.dragonRed):blend(palette.dragonBlack3, 0.92):to_hex(),
			warning = palette.dragonYellow,
			warning_light = color(palette.dragonYellow):blend(palette.dragonBlack3, 0.92):to_hex(),
			info = palette.dragonBlue,
			info_light = color(palette.dragonBlue):blend(palette.dragonBlack3, 0.92):to_hex(),
			hint = palette.dragonAqua,
			hint_light = color(palette.dragonAqua):blend(palette.dragonBlack3, 0.92):to_hex(),
		},
		term = {
			black = palette.dragonBlack5,
			red = palette.dragonRed,
			green = palette.dragonGreen,
			yellow = palette.dragonYellow,
			blue = palette.dragonBlue5,
			magenta = palette.dragonPink,
			cyan = palette.dragonAqua,
			white = palette.dragonWhite,
			black_bright = color(palette.dragonBlack5):brighten(0.6):to_hex(),
			red_bright = color(palette.dragonRed):brighten(0.2):to_hex(),
			green_bright = color(palette.dragonGreen):brighten(0.1):to_hex(),
			yellow_bright = color(palette.dragonYellow):brighten(0.2):to_hex(),
			blue_bright = color(palette.dragonBlue5):brighten(0.3):to_hex(),
			magenta_bright = color(palette.dragonPink):brighten(0.2):to_hex(),
			cyan_bright = color(palette.dragonAqua):brighten(0.1):to_hex(),
			white_bright = color(palette.dragonWhite):brighten(0.2):to_hex(),
			indexed1 = palette.dragonOrange,
			indexed2 = palette.dragonRed,
		},
	}
end

return M
