# -----------------------------------------------------------------------------
# Kanagawa Paper Ash
# Upstream: https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/wezterm/kanagawa-paper-ash.toml
# URL: https://wezterm.org/config/appearance.html
# -----------------------------------------------------------------------------

[colors]
foreground = "#c5c9c5"
background = "#181616"
cursor_bg = "#c4b28a"
cursor_border = "#c4b28a"
cursor_fg = "#181616"
selection_bg = "#393836"
selection_fg = "#c5c9c5"
split = "#8992a7"
compose_cursor = "#8ea49e"
scrollbar_thumb = "#393836"

ansi = [
  "#393836",
  "#c4746e",
  "#699469",
  "#c4b28a",
  "#658594",
  "#a292a3",
  "#8ea49e",
  "#C8C093",
]
brights = [
  "#aca9a4",
  "#cc928e",
  "#72a072",
  "#d4c196",
  "#698a9b",
  "#b4a7b5",
  "#96ada7",
  "#d5cd9d",
]

[colors.indexed]
16 = "#b6927b"
17 = "#c4746e"

[colors.tab_bar]
background = "#282727"
inactive_tab_edge = "#658594"

[colors.tab_bar.active_tab]
fg_color = "#c4b28a"
bg_color = "#181616"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#717C7C"
bg_color = "#282727"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#a292a3"
bg_color = "#181616"

[colors.tab_bar.new_tab]
fg_color = "#717C7C"
bg_color = "#282727"

[colors.tab_bar.new_tab_hover]
fg_color = "#a292a3"
bg_color = "#181616"
intensity = "Bold"

[metadata]
name = "kanagawa-paper-ash"
author = "Simon Ho"
origin_url = "https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/wezterm/kanagawa-paper-ash.toml"
