# -----------------------------------------------------------------------------
# Kanagawa Paper Ash
# Upstream: https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/alacritty/kanagawa-paper-ash.toml
# URL: https://github.com/alacritty/alacritty
# -----------------------------------------------------------------------------

[colors.primary]
background = '#181616'
foreground = '#c5c9c5'

[colors.cursor]
cursor = '#c4b28a'
text = '#181616'

[colors.selection]
background = '#393836'
foreground = '#717C7C'

[colors.normal]
black = '#393836'
red = '#c4746e'
green = '#699469'
yellow = '#c4b28a'
blue = '#658594'
magenta = '#a292a3'
cyan = '#8ea49e'
white = '#C8C093'

[colors.bright]
black = '#aca9a4'
red = '#cc928e'
green = '#72a072'
yellow = '#d4c196'
blue = '#698a9b'
magenta = '#b4a7b5'
cyan = '#96ada7'
white = '#d5cd9d'

[[colors.indexed_colors]]
index = 16
color = '#b6927b'

[[colors.indexed_colors]]
index = 17
color = '#c4746e'
